vscode-python:
  image:
    repository: PaulineMauryL/sdd-poc-server
    tag: "1.0.1"
    pullPolicy: Always
  ingress:
    enabled: true
    hostname: myshinyapp.lab.sspcloud.fr
  # s3:
  #  enabled: true
  #  existingSecret: myshinyapp-s3
  resources: {}
